# ðŸ“Š ServiceSprint â€“ Etapa de EDA

## 1. ImportaÃ§Ã£o de Bibliotecas

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# ConfiguraÃ§Ãµes de exibiÃ§Ã£o
pd.set_option('display.max_columns', None)
sns.set(style="whitegrid")

## 2. Leitura e VisualizaÃ§Ã£o Inicial do Dataset

In [18]:
# Caminho para o arquivo tratado
df = pd.read_csv('../data/Technical Support Dataset.csv')

In [19]:
# Visualiza as primeiras linhas
df.head()

,Status,Ticket ID,Priority,Source,Topic,Agent Group,Agent Name,Created time,Expected SLA to resolve,Expected SLA to first response,First response time,SLA For first response,Resolution time,SLA For Resolution,Close time,Agent interactions,Survey results,Product group,Support Level,Country,Latitude,Longitude
0,Closed,1012,Low,Email,Feature request,1st line support,Kristos Westoll,2023-01-02 00:58:36,2023-01-04 00:58:36,2023-01-02 01:58:36,2023-01-02 01:03:17.432,Within SLA,2023-01-04 00:31:51.694,Within SLA,2023-01-04 04:02:59.013,1.0,3.0,Custom software development,Tier 1,Republic of Ireland,53.094024,-8.019675
1,In progress,1013,High,Phone,Product setup,2nd line support,Adolpho Messingham,2023-01-02 07:27:25,2023-01-04 07:27:25,2023-01-02 07:29:25,2023-01-02 07:27:43.231,Within SLA,NaN,SLA Violated,NaN,3.0,NaN,Other,Tier 2,Italy,43.036776,12.678565
2,Resolved,1014,Low,Chat,Purchasing and invoicing,1st line support,Bernard Beckley,2023-01-02 06:59:04,2023-01-03 06:59:04,2023-01-02 07:01:04,2023-01-02 06:59:57.471,Within SLA,2023-01-02 22:45:32.974,Within SLA,NaN,2.0,NaN,Custom software development,Tier 1,Austria,47.696472,13.345735
3,Closed,1015,Medium,Email,Pricing and licensing,1st line support,Connor Danielovitch,2023-01-03 03:09:39,2023-01-05 03:09:39,2023-01-03 04:09:39,2023-01-03 07:09:15.835,SLA Violated,2023-01-04 14:32:34.979,Within SLA,2023-01-08 04:24:54.771,10.0,4.0,Ready to use Software,Tier 1,Spain,39.673370,-4.767726
4,Closed,1016,Low,Email,Product setup,1st line support,Kristos Westoll,2023-01-03 00:03:58,2023-01-05 00:03:58,2023-01-03 01:03:58,2023-01-03 00:08:01.684,Within SLA,2023-01-04 12:03:05.986,Within SLA,2023-01-06 06:05:08.637,1.0,2.0,Other,Tier 1,Austria,47.696472,13.345735

In [20]:
# Estrutura da base
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2330 entries, 0 to 2329
Data columns (total 22 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Status                          2330 non-null   object
 1   Ticket ID                       2330 non-null   int64
 2   Priority                        2330 non-null   object
 3   Source                          2330 non-null   object
 4   Topic                           2330 non-null   object
 5   Agent Group                     2330 non-null   object
 6   Agent Name                      2330 non-null   object
 7   Created time                    2330 non-null   object
 8   Expected SLA to resolve         2330 non-null   object
 9   Expected SLA to first response  2330 non-null   object
 10  First response time             2312 non-null   object
 11  SLA For first response          2330 non-null   object
 12  Resolution time                 1912 non-null   object
 13  SLA For Resolution              2330 non-null   object
 14  Close time                      1173 non-null   object
 15  Agent interactions              2312 non-null   float64
 16  Survey results                  1173 non-null   float64
 17  Product group                   2330 non-null   object
 18  Support Level                   2330 non-null   object
 19  Country                         2330 non-null   object
 20  Latitude                        2330 non-null   float64
 21  Longitude                       2330 non-null   float64
dtypes: float64(4), int64(1), object(17)
memory usage: 400.6+ KB

In [21]:
# EstatÃ­sticas gerais
df.describe(include='all')

,Status,Ticket ID,Priority,Source,Topic,Agent Group,Agent Name,Created time,Expected SLA to resolve,Expected SLA to first response,First response time,SLA For first response,Resolution time,SLA For Resolution,Close time,Agent interactions,Survey results,Product group,Support Level,Country,Latitude,Longitude
count,2330,2330.000000,2330,2330,2330,2330,2330,2330,2330,2330,2312,2330,1912,2330,1173,2312.000000,1173.000000,2330,2330,2330,2330.000000,2330.000000
unique,4,NaN,3,3,8,2,8,2330,2330,2330,2312,2,1912,2,1173,NaN,NaN,4,2,12,NaN,NaN
top,Closed,NaN,Low,Email,Product setup,1st line support,Nicola Wane,2023-01-02 00:58:36,2023-01-04 00:58:36,2023-01-02 01:58:36,2023-01-02 01:03:17.432,Within SLA,2023-01-04 00:31:51.694,Within SLA,2023-01-04 04:02:59.013,NaN,NaN,Ready to use Software,Tier 1,Germany,NaN,NaN
freq,1173,NaN,1192,1234,630,1770,367,1,1,1,1,2019,1,1547,1,NaN,NaN,1010,1770,306,NaN,NaN
mean,NaN,2481.857082,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.470156,3.510656,NaN,NaN,NaN,48.260756,9.849723
std,NaN,858.040637,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.130958,1.240361,NaN,NaN,NaN,5.085409,9.814618
min,NaN,1012.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,1.000000,NaN,NaN,NaN,39.368279,-8.019675
25%,NaN,1726.250000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.000000,3.000000,NaN,NaN,NaN,43.036776,2.349014
50%,NaN,2480.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.000000,4.000000,NaN,NaN,NaN,48.864716,12.678565
75%,NaN,3233.750000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.000000,4.000000,NaN,NaN,NaN,52.536273,15.474913
max,NaN,3999.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,60.000000,5.000000,NaN,NaN,NaN,55.378052,25.483304